name: uyab/btoz
author:
  name: Bayu Hendra Winata
  email: uyab.exe@gmail.com
  url: 'http://id-laravel.com'
copyright: 2015 Bayu Hendra Winata
description: Laravel Base Application With Various HTML Template Powered By Bootstrap
